@echo off
echo Installing required packages...
npm install @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome tone
echo Starting the application...
npm start 